---
- name: Clone dotfiles
  hosts: 127.0.0.1
  gather_facts: true

  tasks:
   - name: Clone dotfiles
     ansible.builtin.git:
      repo: https://github.com/rickardc/dotfiles.git
      dest: ~/dotfiles # noqa: latest
      clone: true

   - name: Stow dotfiles
     ansible.builtin.command: "stow . --target {{ ansible_env.HOME }} --verbose=2"
     register: result
     changed_when: 'result.stderr is search("LINK: ")'
