---
- name: Clone dotfiles
  hosts: 127.0.0.1
  gather_facts: true

  tasks:
   - name: Install packages
     become: true
     ansible.builtin.package:
      name:
       - stow

   - name: Make dotfiles directory
     ansible.builtin.file:
      path: "{{ ansible_env.HOME }}/dotfiles"
      state: directory
      mode: u+rwx

   - name: Clone dotfiles
     ansible.builtin.git:
      repo: https://github.com/rickardc/dotfiles.git
      dest: "{{ ansible_env.HOME }}/dotfiles" # noqa: latest
      clone: true

   - name: Stow dotfiles
     ansible.builtin.command: "stow -d '{{ ansible_env.HOME }}/dotfiles' -t '{{ ansible_env.HOME }}' --verbose=2"
     register: result
     changed_when: 'result.stderr is search("LINK: ")'
