---
# Run with ansible-playbook playbooks/local-test.yaml --connection=local
- name: Local test
  hosts: 127.0.0.1
  gather_facts: true

  tasks:

    # Update Packages

    # Install Dev tool
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - zsh
          - stow
          - neofetch
          - cmatrix
          - git
          - gh
          - wget
          - curl
          - tmux
          - neovim
          - gnome-terminal
          - steam-devices
          - ansible
          - ansible-lint
        state: present
        # use_backend: dnf4

    - name: Set zsh default
      become: true
      ansible.builtin.user:
        name: chris
        shell: /bin/zsh

    - name: Install multiple packages
      community.general.flatpak:
        name:
          # other
          - com.github.tchx84.Flatseal
          - md.obsidian.Obsidian
          - org.videolan.VLC

          # browsers
          # - org.mozilla.firefox
          - net.waterfox.waterfox
          - io.gitlab.librewolf-community
          - one.ablaze.floorp

          # chat
          - org.signal.Signal
          - com.discordapp.Discord

        # dev
        # - com.visualstudio.code # not ideal in flatpak
          - com.vscodium.codium
        # - org.gnome.Boxes

        # games
          - org.duckstation.DuckStation
          - com.valvesoftware.Steam
          - net.pcsx2.PCSX2
          - com.fightcade.Fightcade
        remote: flathub
        state: present

    - name: Add the key for the 1Password yum repository
      ansible.builtin.rpm_key:
        key: https://downloads.1password.com/linux/keys/1password.asc
        state: present

    - name: Add the 1Password yum repository
      become: true
      ansible.builtin.yum_repository:
        name: 1password
        description: 1Password Stable Channel
        baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: https://downloads.1password.com/linux/keys/1password.asc

    # Install Dev tool
    - name: Install 1Password
      become: true
      ansible.builtin.package:
        name:
          - 1password
          - 1password-cli
        state: present
