---
- name: Install vs code
  hosts: 127.0.0.1
  gather_facts: true

  tasks:

   - name: Install ansible galaxy
     ansible.builtin.command: ansible-galaxy role install gantsign.visual-studio-code
     changed_when: false

   - name: Include gantsign.visual-studio-code role
     ansible.builtin.include_role:
      name: gantsign.visual-studio-code
     vars:
      gantsign_visual_studio_code_users: # noqa: var-naming[no-role-prefix]
       - username: chris
     when: ansible_pkg_mgr == 'dnf'
