---
# Run with ansible-playbook playbooks/local-test.yaml --connection=local
- name: Local test
  hosts: 127.0.0.1
  gather_facts: true

  tasks:

    - name: Ensure fonts directory
      ansible.builtin.file:
        path: "~/.fonts"
        state: directory

    - name: Hack exists
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Hack*Nerd*Font*Complete*"
      register: hack_exists
      ignore_errors: yes

    - name: Download Hack
      when: hack_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes
