---
# Run with ansible-playbook playbooks/local-test.yaml --connection=local
- name: Local test
  hosts: 127.0.0.1
  gather_facts: true

  tasks:

    # Update Packages


    # Install Dev tool
    - name: Install packages
      become: true
      ansible.builtin.dnf:
        name:
          - zsh
          - stow
          - neofetch
          - cmatrix
          - git
          - gh
          - wget
          - curl
          - tmux
          - neovim
        state: present
        use_backend: dnf4

    - name: Install multiple packages
      community.general.flatpak:
        name:
          - org.mozilla.firefox
          - com.discordapp.Discord
          - io.gitlab.librewolf-community
          - org.videolan.VLC
          - com.visualstudio.code
          - com.vscodium.codium
          - org.gnome.Boxes
          - md.obsidian.Obsidian
          - org.duckstation.DuckStation
          - com.valvesoftware.Steam
          - net.pcsx2.PCSX2
          - org.signal.Signal
        remote: flathub
        state: present

    - name: Add the key for the 1Password yum repository
      ansible.builtin.rpm_key:
        key: https://downloads.1password.com/linux/keys/1password.asc
        state: present

    - name: Add the 1Password yum repository
      become: true
      ansible.builtin.yum_repository:
        name: 1password
        description: 1Password Stable Channel
        baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: https://downloads.1password.com/linux/keys/1password.asc

    # Install Dev tool
    - name: Install 1Password
      become: true
      ansible.builtin.dnf:
        name:
          - 1password
          - 1password-cli
        state: present
        use_backend: dnf4
