---
- name: Update raspberrypi 4
  hosts: pi4
  become: true
  tasks:
    - name: Create test.txt
      ansible.builtin.command: touch test.txt

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install neovim
      ansible.builtin.apt:
        name: neovim
        state: present

    - name: Install neofetch
      ansible.builtin.apt:
        name: neofetch
        state: present

    - name: Install btop
      ansible.builtin.apt:
        name: btop
        state: present
